### ISSUE TITLE
Friendly Array Usage

### ISSUE THREAD

**Issue by JonathanILevi** [ParticlePeter/ErupteD#17]
This may be too complicated / over-verbose for your simple bindings, but using C's norm of array length being separate from the pointer is inconvenient, and allows for some unnecessarily, unsafe code (by D standards).

A helpful (compile-time only) addition would be to union a special Vulkan Array (with `uint` length) within the structs.
```
struct VkArray(T) {
    uint length;
    T* ptr;
}
VkArray!T vkArray(T)(T[] vs) {
    return VkArray!T(
        cast(uint) vs.length,
        vs.ptr,
    );
}
```

Then, as an example:
```
struct VkInstanceCreateInfo {
    VkStructureType              sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    const( void )*               pNext;
    VkInstanceCreateFlags        flags;
    const( VkApplicationInfo )*  pApplicationInfo;
    union {
        struct {
            uint32_t                     enabledLayerCount;
            const( char* )*              ppEnabledLayerNames;
        }
        VkArray!(char*) enabledLayers;
    }
    union {
        struct {
            uint32_t                     enabledExtensionCount;
            const( char* )*              ppEnabledExtensionNames;
        }
        VkArray!(char*) enabledExtensions;
    }
}
```

This would allow for usage like this:
```
VkInstanceCreateInfo createInfo = {
    pApplicationInfo: &appInfo,
    enabledExtensions: vkArray(extensions),
    enabledLayerCount: 0,
    pNext: null,
};
```

**Comment by ParticlePeter** [comment]
Your implementation idea is nice (I trust that it works) but I don't like the general idea:
1. I would not want to implement the auto generation. Right now vk.xml parsing is more or less straight forward, aggregates are populated line by line (context free). Sounds like a nightmare to have to look ahead into whole aggregates, then replace multiple lines with even more lines.
2. The aggregate code would not correspond to the spec any more. I quite often read spec and code (from types.d) side by side. In my opinion the suggested functionality adds visual noise to types.d for a quite low benefit (of saving one line of code for the lib user now and then).
3. Once you start thinking about interface improvements you figure that you can do much better than just d arrays instead of pointer and size, in the sense of actually writing an abstraction layer.
[Here](https://github.com/ParticlePeter/LBMethoD/blob/cdceeeaf3f9384015d498a3a354eb6168dd19ca8/source/gui.d#L1957) is an example how I create a full PSO (for ImGui UI drawing) using my own abstraction layer [V-Drive](https://github.com/ParticlePeter/V-Drive). Another very important advantage of this approach is that I do not have to mess with python but can happily code in D.

But by all means, if you like your idea, give it a try your self, and change the hack out of V-Erupt :-)

**Comment by JonathanILevi** [comment]
Fair enough, I might fork it, or I might not.

It does save more than a single line of code, and in many places (when used fully).

As it is, something like this is bug prone, and not very Dish.
```
VkInstanceCreateInfo createInfo = {
    enabledExtensionCount: 2,
    enabledExtensionNames: ["bla", "oo!"],
};
```

I am not looking for a bloated abstraction layer.  I want low-level concept, not high-level "do it this way".  I also have yet to find a good abstraction layer which does not try to bundle with a windowing library!  (I'll use one of my choosing, thank you!)  If you know of any, please share.

After coming back to the question, though, I realized that I can get my desired functionality with a mixin.  Something like:
```
VkInstanceCreateInfo createInfo = {
    mixin(vkStructArray!"enabledExtensions")(["bla", "oo!"])),
};
```

Thank you for taking time to respond, and thank you for your work on these binding.
