### ISSUE TITLE
How to specific platform specific sub-configuration in dub.sdl/json?

### ISSUE THREAD

**Issue by Swoorup** [ParticlePeter/ErupteD#8]
It looks like subconfiguration dub flag does not support platform attributes

How do you change the subconfiguration for platform extension depending on the platform then?
Currently I have this, but that does not work.

https://github.com/Swoorup/VulkanTriangleD/blob/master/dub.sdl

**Comment by ParticlePeter** [comment]
I think this is more a dub issue then errupted. Please consider asking there, I have no idea.

**Comment by Swoorup** [comment]
I see understandable. What do you think about doing a port of this library 
https://github.com/KhronosGroup/Vulkan-Hpp

I am thinking to do so. It is automatically generated as well.

**Comment by ParticlePeter** [comment]
Honestly not much, I think D can do much better. But it depends what you want to do. If you prioritize learning and getting experience with vulkan (like me) instead of porting something I would strongly suggest writing your own abstraction/toolkit. As an example, compare the amount of code one would have to write to create a PSO with Vulkan-Hpp and [this](https://github.com/ParticlePeter/V-Drive/blob/master/example/01_triangle/pipelines.d) (my WIP abstractions).

**Comment by ParticlePeter** [comment]
Can this issue be closed?

**Comment by Swoorup** [comment]
sure
